<script>
	import { t } from 'svelte-i18n';
	import { onMount } from 'svelte';
	import SEO from '$components/SEO.svelte';
	import Markdown from '$components/Markdown.svelte';
	$: description = $t('projects.description');
	$: title = `${$t('linkprojects')} | Vincent Charlebois`;

	onMount(() => {
		// Shadow content
		console.log('%c━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', 'color: #9900fc; font-weight: bold;');
		console.log('%cPartie 3 : Œuvres et projets de Vincent', 'color: #00ff00; font-size: 18px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px;');
		console.log('%cAnalyse du portfolio', 'color: #ffffff; font-size: 14px; font-style: italic; margin-bottom: 10px;');
		console.log('%c━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', 'color: #9900fc; font-weight: bold;');
		console.log('%c\nUne analyse des projets clés de Vincent Charlebois révèle une trajectoire artistique claire et évolutive. Son travail passe d\'explorations précoces du corps, du travail et du lieu à des installations sophistiquées basées sur les données et, plus récemment, à une synthèse de toute sa pratique par l\'utilisation de l\'intelligence artificielle. Ce portfolio démontre une pratique en maturation qui s\'appuie continuellement sur ses préoccupations thématiques fondamentales. Il est important de noter que le CV formel de l\'artiste était inaccessible lors de la recherche pour ce rapport ; par conséquent, cette analyse est basée sur les projets détaillés dans les documents publics disponibles.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.1 Art performance : Travail, lieu et finalité', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cÉtude de cas : Le pelleteur de gravier (2014)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nL\'une des premières œuvres documentées de Charlebois est une performance de longue durée intitulée Le pelleteur de gravier. La performance, qui s\'est déroulée sur plusieurs jours en octobre 2014 dans le Quartier des spectacles de Montréal, consistait en une action simple et répétitive : l\'artiste, équipé d\'une pelle et d\'une brouette, déplaçait un grand tas de gravier d\'un endroit à un autre. L\'action est explicitement décrite comme n\'ayant « aucun autre but que de déplacer un tas de pierres ». Le cycle de travail se poursuivait jusqu\'à ce que l\'artiste, appelé « le travailleur », soit épuisé, moment auquel le gravier était laissé sur place jusqu\'au début de la session suivante.\n\nCette œuvre est une méditation puissante et dépouillée sur le travail, l\'endurance et la nature de la finalité. En dépouillant l\'acte physique de pelleter de tout objectif productif ou utilitaire, Charlebois met en avant la réalité brute et matérielle du travail lui-même. La performance peut être interprétée sous plusieurs angles : comme une critique sisyphéenne des tâches souvent dénuées de sens et répétitives exigées par les systèmes capitalistes ; comme une concentration quasi zen sur le processus et la présence plutôt que sur le résultat ; ou comme une intervention publique qui remet en question l\'utilisation et la valeur de l\'espace civique. Cette pièce est fondamentale, établissant une base de pratique physique et incarnée et un intérêt pour les systèmes de travail qui sert de contrepoint crucial à ses œuvres ultérieures, plus technologiques.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.2 Net art et œuvres basées sur les données : Perceptualiser l\'environnement', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cÉtude de cas : nodes: Belgrade (2017)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nUn exemple clé de la pratique de Charlebois basée sur les données est le projet de 2017 nodes: Belgrade. Pour cette pièce, il a installé des stations météorologiques à l\'intérieur et à l\'extérieur de la galerie Ostavinska à Belgrade, en Serbie. Ces capteurs ont enregistré avec diligence une gamme de données environnementales, notamment la température, l\'humidité, le bruit, la pression atmosphérique et les niveaux de CO2.\n\nL\'analyse de ce projet repose sur une déclaration cruciale : l\'archive de données créée par les capteurs n\'est pas l\'œuvre d\'art finale elle-même, mais plutôt « la notation pour de futures expériences intermédiatiques ». Cela positionne nodes: Belgrade comme un excellent exemple de son concept de l\'archive comme matériau génératif. Le projet transforme l\'environnement passif et ambiant de la galerie et de ses environs en une source de données active et dynamique. L\'accent se déplace du corps de l\'artiste, comme on le voit dans Le pelleteur de gravier, vers le monde invisible des données environnementales capturées par le corps du capteur. Cette œuvre jette les bases conceptuelles et techniques de ses projets de « perceptualisation » ultérieurs et plus complexes en établissant une méthodologie de capture du flux environnemental comme médium créatif.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%cÉtude de cas : La couleur de Montréal (2024)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nDans cette œuvre plus récente et ambitieuse, Charlebois étend sa pratique de collecte de données à l\'échelle de la ville entière. La couleur de Montréal est une installation générative qui « met en couleur les dynamiques météorologiques de la ville » en capturant les variations changeantes du ciel à travers le réseau public de caméras de circulation de Montréal. L\'œuvre fusionne ces images capturées avec du texte pour créer ce qui est décrit comme une « métanarration urbaine ».\n\nCe projet démontre une stratégie artistique sophistiquée de réaffectation des infrastructures publiques existantes. Il prend un système conçu pour la surveillance et le contrôle du trafic et subvertit sa fonction utilitaire, le transformant en un outil de contemplation esthétique et de narration poétique. L\'inspiration explicite de l\'œuvre est l\'essai influent d\'Ursula K. Le Guin, The Carrier Bag Theory of Fiction. Cette référence est une clé philosophique profonde de la pièce. Le Guin s\'oppose aux récits héroïques et linéaires (la lance) en faveur d\'histoires qui agissent comme des contenants pour collecter et conserver des choses disparates (le sac de transport). À cette lumière, l\'installation de Charlebois agit comme un sac de transport pour les moments atmosphériques de la ville, collectant et préservant les nuances fugaces du ciel urbain plutôt que de les forcer dans une seule histoire dramatique. C\'est une exécution magistrale de la « perceptualisation des données environnementales » à l\'échelle métropolitaine.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.3 IA et esthétique régénérative : L\'avenir du paysage', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cÉtude de cas : La fabrication de forêts futures (2024)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nL\'œuvre la plus significative détaillée dans les documents disponibles est sans doute La fabrication de forêts futures, car elle représente une synthèse puissante de tous les thèmes et expériences fondamentaux de Charlebois. La pièce est une projection vidéo d\'une heure affichant un flux continu et fluide de paysages forestiers synthétiques. Ces « forêts futures » ne sont pas des animations mais sont générées par un Réseau Antagoniste Génératif (GAN), une forme d\'intelligence artificielle, spécifiquement le modèle StyleGAN.\n\nLa brillance conceptuelle du projet réside dans la source des données d\'entraînement de l\'IA. Le modèle a été entraîné exclusivement par l\'artiste sur sa propre archive photographique personnelle de dix ans documentant les paysages canadiens transformés par l\'industrie forestière — en particulier les coupes à blanc dont il a été témoin et dans lesquelles il a travaillé en tant que planteur d\'arbres. Cette décision créative forge un lien indissoluble entre son passé de travail physique intense et son présent d\'art technologique avancé.\n\nL\'œuvre est une profonde contemplation de la disparition et de la régénération, de la mémoire et de l\'invention. En nourrissant l\'IA de milliers d\'images de ce qu\'il appelle des « paysages dévastés », il incite la machine à rêver de nouvelles forêts potentielles, créant un flux infini de ce qui « pourrait naître de la réinvention suivant la perte ». Ce projet est l\'aboutissement de sa trajectoire artistique. Il passe du corps (Le pelleteur), à la collecte de données (nodes), pour aboutir à une synthèse finale et sophistiquée où l\'expérience incarnée de l\'artiste devient le « fantôme dans la machine » essentiel, l\'âme poétique de son système génératif. Il explore magistralement les « interconnexions » des cycles naturels et technologiques, posant des questions complexes et urgentes sur ce qui constitue la « nature » à une époque de perte écologique profonde et de médiation technologique puissante.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.4 Pédagogie et partage des connaissances', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cAtelier : Perceptualisation des données environnementales (ISEA2022)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nLa pratique de Charlebois s\'étend au domaine pédagogique, comme en témoigne un atelier qu\'il a dirigé pour le Symposium International sur l\'Art Électronique (ISEA) de 2022. Intitulé « Perceptualisation des données environnementales », l\'objectif de l\'atelier était d\'initier les participants aux « outils et stratégies de codage open-source » pour créer des assemblages médiatiques originaux à partir de données météorologiques. Le résumé de l\'atelier pose des questions évocatrices qui encapsulent sa méthode artistique : « Quel est le son de 38 °C? Est-ce la forme des niveaux de CO2? Comment les variations d\'humidité peuvent-elles être exprimées par la fréquence? ».\n\nCe travail éducatif est une application pratique de sa recherche artistique. Il sert à démystifier les technologies complexes et à donner à d\'autres les moyens de s\'engager dans des recherches créatives similaires. En transformant ses propres méthodes en une boîte à outils partageable basée sur des principes open-source, il cultive activement une communauté de pratique autour de ses thèmes centraux. Cet acte d\'enseignement renforce l\'éthos collaboratif et non propriétaire observé dans ses actions civiques et ses affiliations professionnelles, et il représente un engagement non seulement à faire de l\'art, mais aussi à élargir le champ des artistes capables de le faire.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', 'color: #9900fc; font-weight: bold;');
	});
</script>

<SEO {title} {description} />

<main id="main-content" class="flex flex-col place-items-center justify-center min-h-[75vh]">
	<div class="m-2 px-4 md:m-6 md:px-8 text-left">
		<Markdown content={$t('projects_A')} className="markdown" />
	</div>
</main>
