<script>
	import { t } from 'svelte-i18n';
	import { onMount } from 'svelte';
	import SEO from '$components/SEO.svelte';
	import Markdown from '$components/Markdown.svelte';
	$: description = $t('projects.description');
	$: title = `{$t('linkprojects')} Vincent Charlebois`;

	onMount(() => {
		// Shadow content
		console.log('%c━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', 'color: #9900fc; font-weight: bold;');
		console.log('%cPart 3: Vincent\'s Work and Projects', 'color: #00ff00; font-size: 18px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px;');
		console.log('%cA Portfolio Analysis', 'color: #ffffff; font-size: 14px; font-style: italic; margin-bottom: 10px;');
		console.log('%c━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', 'color: #9900fc; font-weight: bold;');
		console.log('%c\nAn analysis of Vincent Charlebois\'s key projects reveals a clear and evolving artistic trajectory. His work moves from early explorations of the body, labor, and place into sophisticated data-driven installations and, most recently, to a synthesis of his entire practice through the use of artificial intelligence. This portfolio demonstrates a maturing practice that continually builds upon its core thematic concerns. It is important to note that the artist\'s formal CV was inaccessible during the research for this report; therefore, this analysis is based on projects detailed in the available public materials.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.1 Performance Art: Labor, Place, and Purpose', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cCase Study: Le pelleteur de gravier (The Gravel Shoveller) (2014)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nOne of Charlebois\'s earliest documented works is a durational performance piece titled Le pelleteur de gravier. The performance, which took place over several days in October 2014 in Montreal\'s public Quartier des spectacles, consisted of a simple, repetitive action: the artist, equipped with a shovel and wheelbarrow, moved a large pile of gravel from one location to another. The action is explicitly described as having "no other purpose other than to move a stack of rocks". The cycle of labor would continue until the artist, referred to as "the worker," was exhausted, at which point the gravel would be left in place until the next session began.\n\nThis work is a powerful and stark meditation on labor, endurance, and the nature of purpose. By stripping the physical act of shoveling of any productive or utilitarian goal, Charlebois foregrounds the raw, material reality of work itself. The performance can be interpreted through multiple lenses: as a Sisyphean critique of the often meaningless, repetitive tasks demanded by capitalist systems; as a Zen-like focus on process and presence over outcome; or as a public intervention that questions the use and value of civic space. This piece is foundational, establishing a baseline of physical, embodied practice and an interest in systems of labor that serves as a crucial counterpoint to his later, more technological works.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.2 Net Art and Data-Driven Works: Perceptualizing the Environment', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cCase Study: nodes: Belgrade (2017)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nA key example of Charlebois\'s data-driven practice is the 2017 project nodes: Belgrade. For this piece, he installed weather stations both inside and outside the Ostavinska Gallery in Belgrade, Serbia. These sensors diligently recorded a range of environmental data, including temperature, humidity, noise, atmospheric pressure, and CO2 levels.\n\nThe analysis of this project hinges on a crucial statement: the data archive created by the sensors is not the final artwork itself, but rather "the notation for future intermedia experiences". This positions nodes: Belgrade as a prime example of his concept of the archive as a generative material. The project transforms the passive, ambient environment of the gallery and its surroundings into an active, dynamic data source. The focus shifts from the body of the artist, as seen in Le pelleteur de gravier, to the invisible world of environmental data captured by the body of the sensor. This work lays the conceptual and technical groundwork for his subsequent, more complex "perceptualization" projects by establishing a methodology of capturing environmental flux as a creative medium.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%cCase Study: La couleur de Montréal (The Colour of Montreal) (2024)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nIn this more recent and ambitious work, Charlebois scales his data-gathering practice to the level of the entire city. La couleur de Montréal is a generative installation that "colors the meteorological dynamics of the city" by capturing the sky\'s changing variations through Montreal\'s public network of traffic cameras. The work merges these captured images with text to create what is described as an "urban metanarrative".\n\nThis project demonstrates a sophisticated artistic strategy of repurposing existing public infrastructure. It takes a system designed for surveillance and traffic control and subverts its utilitarian function, transforming it into a tool for aesthetic contemplation and poetic narrative. The explicit inspiration for the work is Ursula K. Le Guin\'s influential essay The Carrier Bag Theory of Fiction. This reference is a profound philosophical key to the piece. Le Guin argues against heroic, linear narratives (the spear) in favor of stories that act as containers for collecting and holding disparate things (the carrier bag). In this light, Charlebois\'s installation acts as a carrier bag for the city\'s atmospheric moments, collecting and preserving the fleeting nuances of the urban sky rather than forcing them into a single, dramatic story. It is a masterful execution of "environmental data perceptualization" on a metropolitan scale.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.3 AI and Regenerative Aesthetics: The Future of Landscape', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cCase Study: La fabrication de forêts futures (The Fabrication of Future Forests) (2024)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nArguably the most significant work detailed in the available materials is La fabrication de forêts futures, as it represents a powerful synthesis of all of Charlebois\'s core themes and experiences. The piece is a one-hour-long video projection displaying a continuous, flowing stream of synthetic forest landscapes. These "future forests" are not animations but are generated by a Generative Adversarial Network (GAN), a form of artificial intelligence, specifically the StyleGAN model.\n\nThe conceptual brilliance of the project lies in the source of the AI\'s training data. The model was trained exclusively by the artist on his own personal, decade-long photographic archive documenting the Canadian landscapes transformed by the forestry industry—particularly the clear-cuts he witnessed and worked in as a tree planter. This creative decision forges an unbreakable link between his past of intense physical labor and his present of advanced technological art.\n\nThe work is a deep contemplation of disappearance and regeneration, memory and invention. By feeding the AI with thousands of images of what he calls "devastated landscapes," he prompts the machine to dream of new, potential forests, creating an endless stream of what "could be born from the reinvention following loss". This project is a culmination of his artistic trajectory. It moves from the body (Le pelleteur), through data collection (nodes), to a final, sophisticated synthesis where the artist\'s embodied experience becomes the essential "ghost in the machine," the poetic soul of his generative system. It masterfully explores the "interconnections" of natural and technological cycles, asking complex and urgent questions about what constitutes "nature" in an age of profound ecological loss and powerful technological mediation.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c3.4 Pedagogy and Knowledge Sharing', 'color: #9900fc; font-size: 16px; font-weight: bold; margin-top: 15px;');
		console.log('%cWorkshop: Environmental Data Perceptualization (ISEA2022)', 'color: #00ff00; font-size: 14px; font-weight: bold; font-style: italic;');
		console.log('%c\nCharlebois\'s practice extends into the pedagogical realm, as demonstrated by a workshop he led for the 2022 International Symposium on Electronic Art (ISEA). Titled "Environmental Data Perceptualization," the workshop\'s goal was to introduce participants to "open-source tools and coding strategies" for creating original media assemblages from weather data. The workshop\'s abstract poses evocative questions that encapsulate his artistic method: "What is the sound of 38 °C? Is this the shape of CO2 levels? How can humidity variations be expressed through frequency?".\n\nThis educational work is a practical application of his artistic research. It serves to demystify complex technologies and empower others to engage in similar creative inquiries. By turning his own methods into a shareable toolkit based on open-source principles, he actively cultivates a community of practice around his core themes. This act of teaching reinforces the collaborative, non-proprietary ethos seen in his civic actions and professional affiliations, and it represents a commitment to not only making art but also to expanding the field of artists capable of making it.\n', 'color: #ffffff; line-height: 1.6;');
		console.log('%c━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', 'color: #9900fc; font-weight: bold;');
	});
</script>

<SEO {title} {description} />

<main id="main-content" class="flex flex-col place-items-center justify-center min-h-[75vh]">
	<div class="m-2 px-4 md:m-6 md:px-8 text-left">
		<Markdown content={$t('projects_A')} className="markdown" />
	</div>
</main>
