name: Deploy to Staging (GitHub Pages + Distributed Press)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build SvelteKit site
        run: npm run build

      - name: Deploy to Distributed Press
        uses: hyphacoop/actions-distributed-press@v1.3.0
        with:
          publish_dir: build
          dp_url: https://dp.chanterelle.xyz
          refresh_token: ${{ secrets.DISTRIBUTED_PRESS_TOKEN }}
          site_url: vincentcharlebois.com
          deploy_http: true
          deploy_hyper: true
          deploy_ipfs: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: gh-pages
